# Generated by Django 5.0.7 on 2026-06-03 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('sports', 'Sports'), ('festival', 'Festival')], default='seminar', max_length=20)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=150)),
                ('capacity', models.IntegerField(default=100)),
                ('registered_students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='registered_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
